### ISSUE TITLE
MAWB-4: Add CircleCI integration

### ISSUE THREAD

**Issue by boroda4436** [boroda4436/mate_academy_wikibot_NOV18#12]
Setup CircleCI Free plan.
See: https://github.com/marketplace/circleci

**Comment by boroda4436** [comment]
May be useful: https://www.youtube.com/watch?v=0OjEx2UzLUI

**Comment by YatKat** [comment]
https://github.com/boroda4436/mate_academy_wikibot_NOV18/pull/36
