### ISSUE TITLE
MAWB-6: configure apache http client

### ISSUE THREAD

**Issue by boroda4436** [boroda4436/mate_academy_wikibot_NOV18#14]
required for using wiki API

**Comment by romaanankin** [comment]
Please, refactor client with YouTube API, you could use link you [Link](https://developers.google.com/youtube/v3/code_samples/java#search_by_keyword) to understand how to achieve proper response

**Comment by boroda4436** [comment]
Refactoring required

**Comment by DmitriyLitvin** [comment]
@boroda4436 I know it
