### ISSUE TITLE
MAWB-8: create a YoutubeResponseDto class

### ISSUE THREAD

**Issue by boroda4436** [boroda4436/mate_academy_wikibot_NOV18#17]
create a Youtube ResponseDto and RequestDto classes that will contain all fields that are present in youtube API response

**Comment by boroda4436** [comment]
@romaanankin @Orbit419 
1. Виберіть функціонал який має бути імплементований (можна взяти те що описав Рома вище, але розбити на пункти 1,2,3...)
2. До кожного функціоналу додайте конкретну URL з Youtube API документації яка буде містити формат запиту і відповіді
3. Базуючись на пункті 2 Руслан імплементує всі RequestDto, Роман імплементує всі ResponseDto

**Comment by romaanankin** [comment]
- [ ] 1)присылает лист List<Videos> videos or List<Links> links  по запросу String string

- [ ] 2)присылать новые видео List<Videos> videos or List<Links> links от каналов на которые ты подписан

- [ ] 3)раз в неделю присылать топ 10 трендов по заданой теме(запросу String string)
